Code correction

diff --git a/deploy/pipelines/02-sap-workload-zone.yaml b/deploy/pipelines/02-sap-workload-zone.yaml
--- a/deploy/pipelines/02-sap-workload-zone.yaml
+++ b/deploy/pipelines/02-sap-workload-zone.yaml
@@ -93,17 +93,73 @@ parameters:
     type:                              boolean
     default:                           true
 
+  #--------------------------------------------------------------------
+  # Change:                                                        
+  #   20230419 MKD
+  #
+  # Notes:
+  #   - Fix typo
+  #   - Add default value
+  #--------------------------------------------------------------------
+  #>>>> START OF DELETION <<<<
+  # - name:                              sap_automation_repo_path
+  #   displayName:                       The local path on the agent where the sap_automation repo can be found
+  #   type:                              string
+
+  # - name:                              config_repo_path
+  #   displayName:                       The local path on the agent where the config repo can be found
+  #   type:                              string
+  #>>>> END   OF DELETION <<<<
+  #>>>> START OF INSERTION <<<<
   - name:                              sap_automation_repo_path
-    displayName:                       The local path on the agent where the sap_automation repo can be found
+    displayName:                       The local path on the agent where the sap-automation repo can be found
     type:                              string
+    default:                           sap-automation
 
   - name:                              config_repo_path
     displayName:                       The local path on the agent where the config repo can be found
     type:                              string
+    default:                           config
+  #>>>> END   OF INSERTION <<<<
+  #--------------------------------------------------------------------
 
   - name:                              test
     type:                              boolean
     default:                           false
+
+  #--------------------------------------------------------------------
+  # Change:                                                        
+  #   20230516 MKD
+  #
+  # Notes:
+  #   - Establish debug framework.
+  #--------------------------------------------------------------------
+  #>>>> START OF INSERTION <<<<
+  - name:                              p_debug
+    displayName:                       Debug Mode
+    type:                              boolean
+    default:                           false
+  #>>>> END   OF INSERTION <<<<
+  #--------------------------------------------------------------------
+
+  #--------------------------------------------------------------------
+  # Change:                                                        
+  #   20230516 MKD
+  #
+  # Notes:
+  #   - Establish debug framework.
+  #   - Configuration should persist independent of branch changes of the 
+  #     code repository.
+  #--------------------------------------------------------------------
+  #>>>> START OF INSERTION <<<<
+variables:
+  - name:                              v_debug
+    value:                             ${{ parameters.p_debug }}
+
+  - name:                              v_config_branch
+    value:                             main
+  #>>>> END   OF INSERTION <<<<
+  #--------------------------------------------------------------------
 
 stages:
   - stage: Deploy_SAP_workload_zone
@@ -126,34 +182,77 @@ stages:
           - template:                  templates\download.yaml
           - task:                      PostBuildCleanup@3
           - bash: |
+              #--------------------------------------4---------------------------------------8
               #!/bin/bash
-              green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m" ; cyan="\e[1;36m"
+
+              #--------------------------------------------------------------------
+              # Change:                                                        
+              #   20230516 MKD
+              #
+              # Notes:
+              #   - Establish debug framework.
+              #--------------------------------------------------------------------
+              #>>>> START OF INSERTION <<<<
+              green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+              debug=$(v_debug)
+              [ "$debug" = True ] && set -x                                                   # Debugging On
+              #>>>> END   OF INSERTION <<<<
+              #--------------------------------------------------------------------
 
               echo "##vso[build.updatebuildnumber]Deploying the SAP Workload zone defined in $(workload_zone_folder)"
 
-                # Check if running on deployer
-                if [ ! -f /etc/profile.d/deploy_server.sh ]; then
-                  echo -e "$green --- Install dos2unix ---$reset"
-                  sudo apt-get -qq install dos2unix
-                  export AZURE_DEVOPS_EXT_PAT=$PAT
-                else
-                  source /etc/profile.d/deploy_server.sh
-                  export AZURE_DEVOPS_EXT_PAT=$PAT
-                fi
+              #--------------------------------------------------------------------
+              # Change:                                                        
+              #   20230419 MKD
+              #
+              # Notes:
+              #   - Define Repository paths.
+              #--------------------------------------------------------------------
+              #>>>> START OF INSERTION <<<<
+              CONFIG_REPO_PATH=$BUILD_REPOSITORY_LOCALPATH/$CONFIG_REPO_PATH                 ; echo "CONFIG_REPO_PATH = $CONFIG_REPO_PATH"
+              SAP_AUTOMATION_REPO_PATH=$BUILD_REPOSITORY_LOCALPATH/$SAP_AUTOMATION_REPO_PATH ; echo "SAP_AUTOMATION_REPO_PATH = $SAP_AUTOMATION_REPO_PATH"
+              #>>>> END   OF INSERTION <<<<
+              #--------------------------------------------------------------------
 
-                if [ ! -f $CONFIG_REPO_PATH/LANDSCAPE/$(workload_zone_folder)/$(workload_zone_configuration_file) ]; then
-                  echo -e "$boldred--- $(workload_zone_configuration_file) was not found ---$reset"
-                  echo "##vso[task.logissue type=error]File $(workload_zone_configuration_file) was not found."
-                  exit 2
-                fi
+              # Check if running on deployer
+              if [ ! -f /etc/profile.d/deploy_server.sh ]; then
+                echo -e "$green --- Install dos2unix ---$reset"
+                sudo apt-get -qq install dos2unix
+                export AZURE_DEVOPS_EXT_PAT=$PAT
+              else
+                source /etc/profile.d/deploy_server.sh
+                export AZURE_DEVOPS_EXT_PAT=$PAT
+              fi
 
-                echo -e "$green--- Checkout $(Build.SourceBranchName) ---$reset"
+              if [ ! -f $CONFIG_REPO_PATH/LANDSCAPE/$(workload_zone_folder)/$(workload_zone_configuration_file) ]; then
+                echo -e "$boldred--- $(workload_zone_configuration_file) was not found ---$reset"
+                echo "##vso[task.logissue type=error]File $(workload_zone_configuration_file) was not found."
+                exit 2
+              fi
 
+              #--------------------------------------------------------------------
+              # Change:                                                        
+              #   20230424 MKD
+              #
+              # Notes:
+              #   - Configuration should persist independent of branch changes of the 
+              #     code repository.
+              #--------------------------------------------------------------------
+              #>>>> START OF DELETION <<<<
+              # echo -e "$green--- Checkout $(Build.SourceBranchName) ---$reset"
+              #   cd $CONFIG_REPO_PATH
+              #   git checkout -q $(Build.SourceBranchName)
+              #   mkdir -p .sap_deployment_automation
+              #>>>> END   OF DELETION <<<<
+              #>>>> START OF INSERTION <<<<
+              echo "##[section]--- Checkout $(v_config_branch) branch in configuration repository ---"
                 cd $CONFIG_REPO_PATH
+                git checkout -q $(v_config_branch)
                 mkdir -p .sap_deployment_automation
-                git checkout -q $(Build.SourceBranchName)
+              #>>>> END   OF INSERTION <<<<
+              #--------------------------------------------------------------------
 
-                echo -e "$green--- Validations ---$reset"
+              echo -e "$green--- Validations ---$reset"
 
                 if [ -z $WL_ARM_SUBSCRIPTION_ID ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined in the $(variable_group) variable group."
@@ -197,6 +296,7 @@ stages:
 
               echo -e "$green--- Convert config file to UX format ---$reset"
                 dos2unix -q LANDSCAPE/$(workload_zone_folder)/$(workload_zone_configuration_file)
+
               echo -e "$green--- Read details ---$reset"
 
                 ENVIRONMENT=$(grep "^environment" LANDSCAPE/$(workload_zone_folder)/$(workload_zone_configuration_file) | awk -F'=' '{print $2}' | xargs)
@@ -572,7 +672,21 @@ stages:
                   git config --global user.email "$(Build.RequestedForEmail)"
                   git config --global user.name "$(Build.RequestedFor)"
                   git commit -m "Added updates from devops deployment $(Build.DefinitionName) [skip ci]"
-                  git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push --set-upstream origin $(Build.SourceBranchName)
+                  #--------------------------------------------------------------------
+                  # Change:                                                        
+                  #   20230419 MKD
+                  #
+                  # Notes:
+                  #   - Configuration should persist independent of branch changes of the 
+                  #     code repository.
+                  #--------------------------------------------------------------------
+                  #>>>> START OF DELETION <<<<
+                  # git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push --set-upstream origin $(Build.SourceBranchName)
+                  #>>>> END   OF DELETION <<<<
+                  #>>>> START OF INSERTION <<<<
+                  git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push --set-upstream origin $(v_config_branch)
+                  #>>>> END   OF INSERTION <<<<
+                  #--------------------------------------------------------------------
                 fi
 
                 if [ -f ${workload_environment_file_name}.md ]; then
